import type { Photo } from "react-photo-album";
import imageManifest from './image-manifest.json';

export type PhotoWithCountry = Photo & {
  country: string;
  dateTaken?: Date;
  relPath: string;
};

type ImageManifestEntry = {
  relPath: string;
  country: string;
  countryFolder: string;
  filename: string;
  title: string;
  alt: string;
  width: number;
  height: number;
  aspectRatio: number;
  dateTaken: string | null;
  responsiveSizes: Array<{ width: number; height: number }>;
  responsiveVariants?: Array<{ width: number; height: number; src: string; size: number }>;
};

type ImageManifest = {
  generatedAt: string;
  breakpoints: number[];
  images: Record<string, ImageManifestEntry>;
};

const manifest = imageManifest as ImageManifest;

// Lazy import functions for images (vite will transform these to optimized WebP)
const IMAGE_MODULES = import.meta.glob<string>(
  '../assets/images/*/*.{jpg,jpeg,png,webp}',
  {
    eager: false,
    import: 'default',
    query: {
      format: 'webp',
      quality: '80',
      w: '1920',
    },
  }
);

// Build a map from relPath to import function
const IMAGE_IMPORT_MAP = new Map<string, () => Promise<string>>();
for (const [path, importFn] of Object.entries(IMAGE_MODULES)) {
  // Extract relative path like "japan/tokyo-skyline.png" from "../assets/images/japan/tokyo-skyline.png"
  const match = path.match(/\.\.\/assets\/images\/(.+)$/);
  if (match) {
    IMAGE_IMPORT_MAP.set(match[1].toLowerCase(), importFn as () => Promise<string>);
  }
}

function sortPhotosByDate(photos: PhotoWithCountry[]): PhotoWithCountry[] {
  return photos.sort((a, b) => {
    const aTime = a.dateTaken?.getTime();
    const bTime = b.dateTaken?.getTime();
    
    if (aTime && bTime) return bTime - aTime;
    if (aTime && !bTime) return -1;
    if (!aTime && bTime) return 1;
    
    return a.src.localeCompare(b.src);
  });
}

async function loadSinglePhoto(entry: ImageManifestEntry): Promise<PhotoWithCountry | null> {
  const { width, height, title, alt, country, relPath, dateTaken, responsiveVariants, responsiveSizes } = entry;
  
  // Prefer responsive variants if available (generated by npm run images:optimize)
  // Otherwise fall back to the Vite-processed image
  if (responsiveVariants && responsiveVariants.length > 0) {
    // Use the largest variant as the main src
    const largest = responsiveVariants[responsiveVariants.length - 1];
    
    // Build srcSet using the pre-generated responsive images
    const srcSet = responsiveVariants.map((variant) => ({
      src: variant.src,
      width: variant.width,
      height: variant.height,
    }));
    
    return {
      src: largest.src,
      width,
      height,
      alt,
      title,
      country,
      relPath,
      dateTaken: dateTaken ? new Date(dateTaken) : undefined,
      srcSet,
    };
  }
  
  // Fallback: use Vite-processed image (for development or if responsive images not generated)
  const importFn = IMAGE_IMPORT_MAP.get(entry.relPath.toLowerCase());
  
  if (!importFn) {
    console.warn(`[Photo Loader] No import function for ${entry.relPath}`);
    return null;
  }
  
  try {
    const src = await importFn();
    
    if (!src) {
      console.warn(`[Photo Loader] No source for ${entry.relPath}`);
      return null;
    }
    
    // Build srcSet using pre-computed responsive sizes (same src, different dimensions for layout)
    const srcSet = responsiveSizes.map((size) => ({
      src,
      width: size.width,
      height: size.height,
    }));
    
    return {
      src,
      width,
      height,
      alt,
      title,
      country,
      relPath,
      dateTaken: dateTaken ? new Date(dateTaken) : undefined,
      srcSet,
    };
  } catch (error) {
    console.error(`[Photo Loader] Failed to load ${entry.relPath}:`, error);
    return null;
  }
}

async function loadMultiplePhotos(
  entries: ImageManifestEntry[],
  sort: boolean = false
): Promise<PhotoWithCountry[]> {
  const results = await Promise.all(entries.map(loadSinglePhoto));
  const validPhotos = results.filter((photo): photo is PhotoWithCountry => photo !== null);
  return sort ? sortPhotosByDate(validPhotos) : validPhotos;
}

export async function createPhotosByPaths(paths: string[]): Promise<PhotoWithCountry[]> {
  if (paths.length === 0) return [];

  const pathOrder = new Map(paths.map((path, idx) => [path.toLowerCase(), idx]));
  
  // Get entries from manifest
  const entries = paths
    .map(path => manifest.images[path.toLowerCase()])
    .filter((entry): entry is ImageManifestEntry => entry !== undefined);
  
  const photos = await loadMultiplePhotos(entries, false);
  
  return photos.sort((a, b) => {
    const orderA = pathOrder.get(a.relPath.toLowerCase()) ?? 999;
    const orderB = pathOrder.get(b.relPath.toLowerCase()) ?? 999;
    return orderA - orderB;
  });
}

export async function createPhotosByLocation(location: string): Promise<PhotoWithCountry[]> {
  const normalizedLocation = location.toLowerCase();
  
  // Get all entries for this location from manifest
  const entries = Object.values(manifest.images).filter(
    (entry) => entry.countryFolder.toLowerCase() === normalizedLocation
  );
  
  return loadMultiplePhotos(entries, true);
}

export async function getLocationMetadata(): Promise<Record<string, { heroImage: string | null }>> {
  const heroEntries = new Map<string, ImageManifestEntry>();
  const metadata: Record<string, { heroImage: string | null }> = {};
  
  for (const entry of Object.values(manifest.images)) {
    const countryKey = entry.country.toLowerCase();
    
    if (!heroEntries.has(countryKey)) {
      heroEntries.set(countryKey, entry);
      metadata[countryKey] = { heroImage: null };
    }
  }
  
  const heroPhotos = await loadMultiplePhotos(Array.from(heroEntries.values()), false);
  
  for (const photo of heroPhotos) {
    const countryKey = photo.country.toLowerCase();
    metadata[countryKey] = { heroImage: photo.src };
  }
  
  return metadata;
}
